---
- name: Install and configure Nginx
  hosts: all
  become: true
  tasks:

    - name: Install prerequisites
      apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - ubuntu-keyring
        state: present
        update_cache: yes

    - name: Import the official Nginx signing key
      ansible.builtin.command:
        cmd: >
          curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor
          > /usr/share/keyrings/nginx-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: Verify the Nginx signing key fingerprint
      ansible.builtin.shell:
        cmd: >
          gpg --dry-run --quiet --no-keyring --import --import-options import-show
          /usr/share/keyrings/nginx-archive-keyring.gpg | grep "573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62"
      register: gpg_verification
      failed_when: gpg_verification.rc != 0

    - name: Add the Nginx stable repository
      ansible.builtin.shell:
        cmd: >
          echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg]
          http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx"
          > /etc/apt/sources.list.d/nginx.list
      args:
        creates: /etc/apt/sources.list.d/nginx.list

    # Uncomment the following section if you want to use the mainline Nginx repository
    # - name: Add the Nginx mainline repository
    #   ansible.builtin.shell:
    #     cmd: >
    #       echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg]
    #       http://nginx.org/packages/mainline/ubuntu $(lsb_release -cs) nginx"
    #       > /etc/apt/sources.list.d/nginx.list
    #   args:
    #     creates: /etc/apt/sources.list.d/nginx.list

    - name: Set up repository pinning
      copy:
        dest: /etc/apt/preferences.d/99nginx
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
